### ISSUE TITLE
Behat + Selenium + GeckoDriver - Opens firefox and loads page but cant find content.

### ISSUE THREAD

**Issue by Ghostff** [mozilla/geckodriver#1548]
## System

* Version: v0.24.0
* Platform: Linux
* Firefox: 66.0.3 (64-bit)
* Selenium: 3.141.59

### behat.yml
```yml
default:
  autoload:
    '': tests/behat/bootstrap
  suites:
    default:
      paths:
        features: "%paths.base%/tests/behat/"
      contexts:
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
        - BehatContexts\FeatureContext
  extensions:
    Behat\MinkExtension:
      base_url: https://www.wikipedia.org/
      browser_name: chrome
      goutte: ~
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
        browser: chrome
        capabilities:
          marionette: true

firefox:
  extensions:
    Behat\MinkExtension:
      base_url: https://www.wikipedia.org/
      browser_name: firefox
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
        browser: firefox
        capabilities:
          marionette: true

```
### Test feature
```
@javascript
Scenario: Searching for a page that does exist
  Given I am on "/wiki/Main_Page"
   When I fill in "search" with "Behavior Driven Development"
    And I press "searchButton"
   Then I should see "agile software development"
```

### starting selenium
```
java -jar  -Dwebdriver.gecko.driver=tests/behat/drivers/geckodriver -Dwebdriver.chrome.driver=tests/behat/drivers/chromedriver tests/behat/drivers/selenium-server-standalone-3.141.59.jar -log tests/behat/logs/selenium.log > log.txt 2>&1 &
```
### Test attempt output
```
@javascript
Scenario: Searching for a page that does exist               		# tests/behat/search.feature:8
Given I am on "/wiki/Main_Page"                            		# BehatContexts\FeatureContext::visit()
When I fill in "search" with "Behavior Driven Development" 		# BehatContexts\FeatureContext::fillField()

Form field with id|name|label|value|placeholder "search" not found. (Behat\Mink\Exception\ElementNotFoundException)
```
And the above works for `chrome`

### selenium log
```
09:08:22.680 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browser": "firefox",
  "browserName": "firefox",
  "ignoreZoomSetting": false,
  "marionette": true,
  "name": "Behat feature suite",
  "tags": [
    "localhost.localdomain",
    "PHP 7.2.17"
  ]
}
```
