### ISSUE TITLE
Selenium WebDriver: Some scrollbars missing in screenshot

### ISSUE THREAD

**Issue by alexander-nitsche** [mozilla/geckodriver#1908]
## System

* Version: 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)
* Platform: Ubuntu 20.04.2 LTS
* Firefox: 89.0.1
* Selenium: selenium/standalone-firefox:4.0 (2021-06-18T11:03:02)
* Codeception: 4.1.21

## Testcase

When I take a screenshot of the latest TYPO3 backend with the latest codeception + the latest Selenium Firefox standalone container, the scrollbars of an iframe and a [HTML5 custom element](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements) with `overflow-y:scroll` are not rendered, while the scrollbar of a DIV layer is rendered with `overflow:auto`. I would expect to see a rendered scrollbar on the screenshot in all three cases, as is the case when browsing manually in the TYPO3 backend. When using Chrome instead of Firefox, all scrollbars are rendered.

```
$I->makeScreenshot();
```
gives e.g. this screenshot when rendered by firefox (left column is DIV layer, middle is HTML5 custom element, right is iframe):
![StyleguidePageSelectboxOpen](https://user-images.githubusercontent.com/20297232/124500726-8f25a380-ddc0-11eb-8d49-edcc2e250a8e.png)

and this when rendered by chrome:
![StyleguidePageSelectboxOpen](https://user-images.githubusercontent.com/20297232/124500590-5259ac80-ddc0-11eb-999c-a0f5261982e6.png)

## Stacktrace

No error produced. Screenshot is incomplete.

## Trace-level log

No trace log producted.

**Comment by whimboo** [comment]
@alexander-nitsche does the scrollbar of the HTML5 custom element appear when you load that page in Firefox? If yes, do you have a chance to create a minimized HTML testcase for that particular issue? Without some actual code it will be hard to investigate.

**Comment by alexander-nitsche** [comment]
The problem seems to be not with the custom element, but with its css `overflow-y:scroll` - in contrary to `overflow:auto`, which works.

Minimal example:

codeception.yml
```yaml
env:
  ..
  firefox:
    modules:
      enabled:
        - WebDriver:
            url: http://web
            browser: firefox
            wait: 1
            host: firefox
            capabilities:
              moz:firefoxOptions:
                args: [ "-headless" ]
```

scrollbars.html
```html
<html>
<body style="background-color:grey;">
<h1 style="height:40px;">Scrollbars</h1>

<!-- DIV layer with overflow:auto works -->
<div style="width:200px;height:260px;background-color:green;overflow:auto;float:left;">
    Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>
    Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>
</div>

<!-- IFrame fails -->
<iframe src="./scrollbarsIframe.html" style="width:200px;height:260px;background-color:blue;float:left;"></iframe>

<!-- DIV layer with overflow-y:scroll fails -->
<div style="width:200px;height:260px;background-color:orange;overflow-y:scroll;float:left;">
    Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>
    Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>
</div>

</body>
</html>
```

scrollbarsIframe.html
```html
<html>
<body>
Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>
Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>Text<br>
</body>
</html>
```

ScrollbarsCest
```php
..
$I->amOnUrl("http://web/scrollbars.html");
$I->canSee("Scrollbars");
$I->makeScreenshot();
```
and results in 
![Scrollbars](https://user-images.githubusercontent.com/20297232/124516214-724d9800-dde1-11eb-821d-fe4a7cb21729.png)
instead of
![Scrollbars](https://user-images.githubusercontent.com/20297232/124516279-8f826680-dde1-11eb-9995-d4447eb9f448.png)

**Comment by whimboo** [comment]
Thanks for the testcase! That's helpful.

The screenshot via geckodriver works perfectly fine for me on macOS. For all three iframes the scrollbars are visible. As such I wonder if that might be related to your local system eg. grraphics driver and such. So here some ideas for further investigation:

1. Does the same happen when you are using the Firefox internal screenshot feature? Just load the given testcase and then open the context menu at any position on this page. Click on `Take Screenshot` and select `Save visible` at the top right corner.
2. Check if your graphics drivers are up-to-date.
3. Check if this might be related to WebRender. [This page has some nice tips](https://www.ghacks.net/2020/12/14/how-to-find-out-if-webrender-is-enabled-in-firefox-and-how-to-enable-it-if-it-is-not/) for playing with different modes.

**Comment by alexander-nitsche** [comment]
Locally i use Debian Buster with Firefox ESR 78.11.0esr (64-bit) which captures a fine screenshot of the given three scrollbars. 

The problem seems to be in the combination of the Selenium + Geckodriver + Firefox in the docker image 
```
bf889630d95a selenium/standalone-firefox 4.0
``` 
of the latest selenium release: https://github.com/SeleniumHQ/docker-selenium/releases. 

Can you take a proper screenshot via that docker image of the given three scrollbars?

**Comment by whimboo** [comment]
If it's only happening in the docker image please check the steps that I mentioned in the last comment. The problem here doesn't seem to be related to geckodriver, and Marionette but Firefox itself. So if none of the above steps help, you should file a Firefox specific bug on Bugzilla.

**Comment by alexander-nitsche** [comment]
Enabling and disabling WebRender via 
```
  firefox:
    modules:
      enabled:
        - WebDriver:
            http://web
            browser: firefox
            wait: 1
            host: firefox
            capabilities:
              moz:firefoxOptions:
                args: [ "-headless" ]
                prefs:
                  gfx.webrender.force-disabled: true
```
did not make a difference in the screenshot, but for the logs of the docker container. With WebRender it logs a lot of 
```
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt`)
```

Do you propose to head to the Firefox Bugzilla or to the Selenium GitHub next?
